### ISSUE TITLE
Use CLI to add options to certain modules.

### ISSUE THREAD

**Issue by albexl** [albexl/data-structures-for-teaching#12]
Maybe we should allow the input of parameters through CLI. We could start by adding it to the [graphics.py](https://github.com/albexl/data-structures-for-teaching/blob/dev/data_structures/trie/graphics.py) file so we can specify where to store the visual representation of the trie.

My recommendation would be to use the `argparse` library for this purpose.

**Comment by leynier** [comment]
I recommend you use [Typer](https://github.com/tiangolo/typer) from the same creator of [FastAPI](https://github.com/tiangolo/fastapi) (@tiangolo)

https://typer.tiangolo.com

**Comment by albexl** [comment]
@leynier I didn't give it a thorough look. But so far, it seems so easy to use. Thank you very much.

I will leave this issue open for now, in case somebody wants to share another library.
