### ISSUE TITLE
Add the priority queue implementation

### ISSUE THREAD

**Issue by albexl** [albexl/data-structures-for-teaching#14]

**Comment by albexl** [comment]
@gabyarte should we remove this issue now that you added the Heap implementation? Or are priority queues different from heaps somehow? Maybe heaps are used to implement priority queues? Not quite sure about the difference.

**Comment by gabyarte** [comment]
@albexl I think the idea behind heap and priority queue are the same. According to some pages, the priority queue is based on the queue structure, while the heap is based on a tree structure ([[1]](https://www.hackerearth.com/practice/notes/heaps-and-priority-queues/)). In other references, it isn't clear the real difference and, in fact, the priority queue is implemented using a binary heap ([[2]](https://www.cs.cmu.edu/~rdriley/121/notes/heaps.html), [[3]](https://www.geeksforgeeks.org/priority-queue-using-binary-heap/)).

Given all these facts, I would say that this issue can be closed, but I leave it to your consideration.

**Comment by albexl** [comment]
Closed it is.
