### ISSUE TITLE
Comparison Function Type

### ISSUE THREAD

**Issue by cmglezpdev** [albexl/data-structures-for-teaching#33]
In some algorithms it is important to know if two objects are equal or if one is less strict than the other. You have to define the return type of the comparison function (number or boolean, preferably number) because there are cases in which this information is needed and I think it is not good to leave it open.

For example. if you change all comparison function from the tests by 
```py
lambda x, y: x - y
```
Many tests will be wrong. For that, should be define the function type, change the test and fix the algorithms and data structures implementations that are afected.

**Comment by albexl** [comment]
> In some algorithms it is important to know if two objects are equal or if one is less strict than the other. You have to define the return type of the comparison function (number or boolean, preferably number) because there are cases in which this information is needed and I think it is not good to leave it open.
> 
> For example. if you change all comparison function from the tests by
> 
> ```python
> lambda x, y: x - y
> ```
> 
> Many tests will be wrong. For that, should be define the function type, change the test and fix the algorithms and data structures implementations that are afected.

I don't seem to understand the example that you are showing. I know you can define a comparison function so it returns integer values, usually `-1`, `0` or `1`, but so far it is being handled with boolean comparison functions that define a `partial order` on the set as far as I can tell. Of course, there is no check to ensure that the comparison function is well-defined, so maybe we should try to fix that. It can be an interesting thing to do.

But, if you could show an example where a boolean comparison function doesn't work with the sorting implementations we have, it would be great. Also, if for some sorting algorithm it is absolutely necessary to define the equality criteria, we can add it as a specific property of that class, and maybe that way we don't change the entire mechanism we have for more general comparison functions.

What do you think? Did I explain myself clearly? Don't hesitate to ask any questions.

Also, if this topic gets bigger we can consider moving it to the `discussions` section.

**Comment by cmglezpdev** [comment]
I've been thinking about this and you're right. Any combination that we need, can to do them with the partial order relation `<`.

**Comment by albexl** [comment]
@cmglezpdev  Should we close this issue then? And try to stick with boolean comparison functions at the moment. It can be reopened if we find a case that doesn't fit this strategy.
