### ISSUE TITLE
Searching Algorithms

### ISSUE THREAD

**Issue by cmglezpdev** [albexl/data-structures-for-teaching#39]
I started to implement the structure of the sorting methods in this PR #38

**Comment by albexl** [comment]
I will check it today. 

But, as a recommendation, I would prefer to go little by little, trying to make things work properly under a well-thought class architecture. So, I would say, maybe start with the linear search in that PR and then, one at a time, start with the rest. This way it will be easier to keep track of changes and correct design issues.
