### ISSUE TITLE
Using a more convenient dependency management tool

### ISSUE THREAD

**Issue by acuriel** [albexl/data-structures-for-teaching#44]
**Is your feature request related to a problem? Please describe.**
PIP and plain `requirements.txt` create some headaches when new versions are released and there are more convenient and modern ways of dependency management for Python

**Describe the solution you'd like**
I would recommend 2 approaches, that could be really helpful and added sequentially:
1. Add more modern dependency management. I would recommend [Poetry](https://python-poetry.org/). It's easy to use, and maintain, and it has been in the industry for a while already
2.  Dockerize the project. This is always convenient. Also, it could help with the animation part. We could use [PyScript](https://pyscript.net/) instead of a desktop app, though I've never used it, so not sure if it's worth it

**Describe alternatives you've considered**
Something we can do at the moment is to fix the versions on the requirements.txt to the last update for each major version

**Additional context**

**Comment by acuriel** [comment]
@albexl I updated the PR, and put it out of `draft`. Take a look at the changes in the contributing file, and let me know if you prefer more details and examples. I will recommend completely removing the file `requirements.txt`, but it'll force everyone to use Poetry. We can leave the requirements.txt, but then we need to update it every time a change in the dependencies occurs.
In any case, it would be recommended to not manually modify the requirements.txt file, unless necessary.

**Comment by albexl** [comment]
@acuriel I just merged your PR. Looks great!

Let's keep the `requirements.txt` for now and make sure we update it using the `poetry` cli.
